services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    env_file:
      - ./frontend/.env

  backend:
    volumes:
      - ./API:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/paginaInstitucional?authSource=admin
    env_file:
      - ./API/.env
