services:
#  mongo:
#    image: mongo:6
#    container_name: mongo32
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: administrador
#      MONGO_INITDB_ROOT_PASSWORD: Esdrujula2022
#    volumes:
#      - mongo_data:/data/db
#    restart: unless-stopped

#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
#      ME_CONFIG_MONGODB_ADMINUSERNAME: administrador
#      ME_CONFIG_MONGODB_ADMINPASSWORD: Esdrujula2022
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_SITE_BASEURL: /mongo
#    depends_on:
#      - mongo
#    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      # PERSISTENCIA: Se mapea la carpeta public completa
        - ./frontend/public/uploads:/app/public/uploads
        - ./frontend/public/docs:/app/public/docs
        - ./frontend/public/images:/app/public/images
        - ./frontend/data:/app/data
    #pends_on:
    #   - api
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: encuesta_db
    restart: always
    environment:
      MYSQL_DATABASE: scrum_eval
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - ./Calificacion_Grupos/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Calificacion_Grupos/users.sql:/docker-entrypoint-initdb.d/users.sql
      - db_data:/var/lib/mysql

  app:
    build: 
      context: ./Calificacion_Grupos
      dockerfile: Dockerfile
    container_name: encuesta_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: scrum_eval
      JWT_SECRET: super-secret-key
    depends_on:
      - db

#  backadmin:
#    build:
#      context: ./BackAdmin
#      dockerfile: Dockerfile
#    container_name: react_backadmin
#    ports:
#      - "5173:5173"
#    stdin_open: true
#    tty: true  
#    volumes:
#      - ./BackAdmin:/app
#      - /app/node_modules
#    depends_on:
#      - mongo
#    restart: unless-stopped
    
#  php:
#    build:
#      context: ./php
#      dockerfile: Dockerfile
#    container_name: php56_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    volumes:
#      - ./php/php.ini:/usr/local/etc/php/php.ini
#    restart: unless-stopped

#  nginx:
#    image: nginx:latest
#    container_name: nginx_proxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - uploads:/var/www/uploads
#      - docs:/var/www/docs
#    depends_on:
#      - frontend
#    restart: unless-stopped

volumes:
  db_data:
  #mongo_data:
  #mysql_data:
  #uploads:
  #images:
  #docs:
  #data:
