
services:
  mongo:
    image: mongo:6
    container_name: mongo32
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped  
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrador
      MONGO_INITDB_ROOT_PASSWORD: Esdrujula2022

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true  
      ME_CONFIG_MONGODB_ADMINUSERNAME: administrador
      ME_CONFIG_MONGODB_ADMINPASSWORD: Esdrujula2022
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - '4000:4000'
    env_file:
      - ./API/.env
    restart: unless-stopped  
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - api

volumes:
  mongo_data:
